### ISSUE TITLE
Need more examples

### ISSUE THREAD

**Issue by LazarenkoA** [xelaj/mtproto#11]
The lack of descriptions for methods and fields of structures makes it very difficult to work with the code, it is difficult to understand something yourself. Please post more working examples, such as getting a contact list, how to send a message to a specific user, etc., such basic things.

**Comment by ololosha228** [comment]
I currently working on examples, stay tuned)

**Comment by LazarenkoA** [comment]
thanks for the translation

**Comment by ololosha228** [comment]
@LazarenkoA take a look at [this branch](https://github.com/xelaj/mtproto/tree/client_rework), hope examples from here will help

**Comment by LazarenkoA** [comment]
but what about sending messages?

**Comment by ololosha228** [comment]
@LazarenkoA use [this method](https://core.telegram.org/method/messages.sendMessage)

examples are for understanding how does this lib works. You can find method for you and call it like others in example dir)
