### ISSUE TITLE
Setting ServerHost has no effect

### ISSUE THREAD

**Issue by patrikhermansson** [xelaj/mtproto#12]
Hi, trying to call `AuthSendCode` after successfully creating a new client gives me the error:  `PHONE_MIGRATE_4 (code 303)`. Indicated in here: https://core.telegram.org/api/errors this is because the account is associated with data center nr 4. Issues is that I've tried all IP addresses that tdlib uses (including nr 4) but none of them work, I get the same error.

Not really sure how to solve this. Is the issue that the specific request need to go to another IP but the client should connect to the standard address given to me when creating the app in the Telegram dev dashboard? Appears that TDlib switches between these endpoints automatically as it has the addresses hard-coded here: https://github.com/tdlib/td/blob/master/td/telegram/net/ConnectionCreator.cpp

Here's the response:

`&serialize.RpcResult{
  ReqMsgID: 6880960152093058776,
  Obj:      &serialize.RpcError{
    ErrorCode:    303,
    ErrorMessage: "PHONE_MIGRATE_4",
  },
}`

Any suggestions on solutions would be much appreciated.

**Comment by patrikhermansson** [comment]
Ok know where it goes wrong. No matter what `ServerHost` you input, `NewMTProto` sets it to `149.154.167.50:443`. When i edited the hard coded ip in that function to the correct one, it worked. 

Seems to be that `LoadSession()` in `session_save.go:63` returns an error when a session file doesn't exist which triggers `NewMTProto` to fall back to the default address. Guess solution is to always retain the input `ServerHost` if it exist.

**Comment by ololosha228** [comment]
Okay, i found this issue on telegram docs: ([from here](https://core.telegram.org/method/auth.sendCode))

When you get this error, you need to automatically switch DC with id X (for you it's 4). I really don't understand why not to add meta info to errors, but... It works _this way_, sadly.

So to fix this problem, we need:

1) make autosetup on several errors like this one;
2) ensure, that MTProto.Client don't have magic constants.

I'm happy to do it myself, but if you want, you can make PR for fixing these problems :smiley:

**Comment by patrikhermansson** [comment]
Exactly! Two separate issues really, need to look into exactly how this works but can attempt to make PR although still need to better understand the structure of the project.

**Comment by ololosha228** [comment]
Discussion moving to #22
