### ISSUE TITLE
Error: Client doesn't have method

### ISSUE THREAD

**Issue by VladPetriv** [xelaj/mtproto#122]
https://github.com/xelaj/mtproto/blob/5eb6237dcf631e69d7694418990b32b333f99586/examples/auth/main.go#L49

Description:
I get an error when try to run example with authorization.
Error say that client doesn't have method or field IsSessionRegistred.

![image](https://user-images.githubusercontent.com/80276277/155181527-7919f9b3-9698-410c-bbf2-8e3a86e2a796.png)

**Comment by erkanom** [comment]
You can find a solution here

https://github.com/xelaj/mtproto/discussions/83#discussioncomment-1932684

**Comment by VladPetriv** [comment]
Thank you)
