### ISSUE TITLE
[FEAT]: telegram.NewClient not working 

### ISSUE THREAD

**Issue by tiulinh** [xelaj/mtproto#145]
i copy code form this prject. i change app_id, app_hash and public key. after runing it throw error:

panic:  (code 4294966892)
goroutine 37 [running]:
github.com/xelaj/mtproto.check(...)
        /Users/test/go/pkg/mod/github.com/xelaj/mtproto@v1.0.1-0.20230703103216-d0f7a8eec0e2/utils.go:50
github.com/xelaj/mtproto.(*MTProto).startReadingResponses.func1()
        /Users/test/go/pkg/mod/github.com/xelaj/mtproto@v1.0.1-0.20230703103216-d0f7a8eec0e2/mtproto.go:277 +0x1c5
created by github.com/xelaj/mtproto.(*MTProto).startReadingResponses
        /Users/test/go/pkg/mod/github.com/xelaj/mtproto@v1.0.1-0.20230703103216-d0f7a8eec0e2/mtproto.go:258 +0xaa

please help me to fix it!
---------------------------------

my code: 
	```
appStorage := utils.PrepareAppStorageForExamples()
	sessionFile := filepath.Join(appStorage, "session.json")
	publicKeys := filepath.Join(appStorage, "tg_public_keys.pem")
	// edit these params for you!
	client, err := telegram.NewClient(telegram.ClientConfig{
		// where to store session configuration. must be set
		SessionFile: sessionFile,
		// host address of mtproto server. Actually, it can be any mtproxy, not only official
		ServerHost: "149.154.167.50:443",
		PublicKeysFile:  publicKeys,
		AppID:           api_id, 
		AppHash:         api_hash, 
		InitWarnChannel: true, 
	})
	dry.PanicIfErr(err)
	client.Warnings = make(chan error) // required to initialize, if we want to get errors
	utils.ReadWarningsToStdErr(client.Warnings)
      //  i checked it is error this code but i don't why?

      	setCode, err := client.AuthSendCode(
		phone, api_id, api_hash, &telegram.CodeSettings{},
	)
	fmt.Println("Ok: ", setCode)
```

**Comment by cfklkj** [comment]
i met the same error

**Comment by quenbyako** [comment]
Closed due to deprecation of first version. If you have same issue with v2 — please, feel free to open new issue 🙏
