### ISSUE TITLE
[BUG]: sending AuthSendCode: recreating connection: can't connect: setup connection: resolving tcp: address 91.108.56.139: missing port in address`

### ISSUE THREAD

**Issue by TNT-ma** [xelaj/mtproto#150]
&errors.withStack{
  error: &errors.withMessage{
    cause: &errors.withStack{
      error: &errors.withMessage{
        cause: &errors.withStack{
          error: &errors.withMessage{
            cause: &errors.withStack{
              error: &errors.withMessage{
                cause: &errors.withStack{
                  error: &errors.withMessage{
                    cause: &net.AddrError{
                      Err:  "missing port in address",
                      Addr: "91.108.56.139",
                    },
                    msg: "resolving tcp",
                  },
                  stack: &errors.stack{
                    0x68b728,
                    0x68c031,
                    0x68ebb6,
                    0x68ea72,
                    0x68eeec,
                    0x69012a,
                    0x68ed1e,
                    0x6a98a6,
                    0x6a97fe,
                    0x6bf4b9,
                    0x438507,
                    0x4670c1,
                  },
                },
                msg: "setup connection",
              },
              stack: &errors.stack{
                0x68c114,
                0x68ebb6,
                0x68ea72,
                0x68eeec,
                0x69012a,
                0x68ed1e,
                0x6a98a6,
                0x6a97fe,
                0x6bf4b9,
                0x438507,
                0x4670c1,
              },
            },
            msg: "can't connect",
          },
          stack: &errors.stack{
            0x68ebfc,
            0x68ea72,
            0x68eeec,
            0x69012a,
            0x68ed1e,
            0x6a98a6,
            0x6a97fe,
            0x6bf4b9,
            0x438507,
            0x4670c1,
          },
        },
        msg: "recreating connection",
      },
      stack: &errors.stack{
        0x68eefd,
        0x69012a,
        0x68ed1e,
        0x6a98a6,
        0x6a97fe,
        0x6bf4b9,
        0x438507,
        0x4670c1,
      },
    },
    msg: "sending AuthSendCode",
  },
  stack: &errors.stack{
    0x6a98df,
    0x6bf4b9,
    0x438507,
    0x4670c1,
  },
}
panic: sending AuthSendCode: recreating connection: can't connect: setup connection: resolving tcp: address 91.108.56.139: missing port in address

**Comment by quenbyako** [comment]
Hey @TNT-ma! Thanks for creating a new bug report!

Standard `net` package always requires port for setting up a new connection, because port resolving is usually is a part of application protocol, not for transport. and MTProto doesn't bind specific ports, like 80 for http, 22 for ssh, etc. **Usually** (but only usually) it's 443 port to bypass port restrictions of firewalls, but protocol doesn't specify for default port, so it's quite problematic to set default by ourselves. 

--------

You might also try a updated version of this package, [MTProto v2.0](https://github.com/xelaj/mtproto/tree/v2.0.0-rc.2), which we didn't release yet, but you might find it useful for any case 😉

**Comment by TNT-ma** [comment]
panic: sending AuthSendCode: recreating connection: can't connect: setup connection: dialing tcp: dial tcp [2001:b28:f23d:f001::a]:443: connect: network is unreachable

**Comment by quenbyako** [comment]
@TNT-ma could you please share the code snippet if it's possible?
