### ISSUE TITLE
Codegen: UNEXPECTEDLY, some Rpc responses are not objects! (see desc)

### ISSUE THREAD

**Issue by quenbyako** [xelaj/mtproto#19]
СукаБлять!

Alright, so some messages like `contacts.getSaved` response as `vector<someType>` (which is actually slices). in MTProto vector is **LIKELY** object (it has 4 bytes for len and bytes stream of wrapped objects).

I changed already decoder of this shit, but we need to fix codegen. Now in `MTProto` object we have two different request types:

`MTProto.MakeRequest(TL)` — for REAL objects
`MTProto.MakeRequestAsSlice(TL, as reflect.Type)` — for responses which is vectors. `as` need for decoder, it's trying to understand, which type of slice do you need

**Comment by ololosha228** [comment]
partially, it's fixed. see #37 for fixes of this bug in codegen tool

**Comment by zweihander** [comment]
@ololosha228 #37 does not fix that issue (well, it can, but ```MakeRequestAsSlice``` is a crap, and I found a better way how to fix it).
I think this issue might be re-opened for a while (new big PR is coming :scream:).

**Comment by ololosha228** [comment]
@zweihander got it

I dont like this solution too, bu i didn't find a way how to make requests without breaking current requesting system. Maybe, if you know how to make it, it's all on you)
