### ISSUE TITLE
panic in mtproto_utils.go 

### ISSUE THREAD

**Issue by LazarenkoA** [xelaj/mtproto#30]
ОС: Windows 10

I use exemple https://github.com/xelaj/mtproto/tree/master/examples/get_saved_contacts
getting panic
```
panic: (*serialize.BadMsgNotification) 0xc0004e20e0 [recovered]
	panic: (*serialize.BadMsgNotification) 0xc0004e20e0

goroutine 19 [running]:
github.com/xelaj/mtproto.(*MTProto).recoverGoroutine(0xc000228360)
	C:/Users/Артем/go/pkg/mod/github.com/xelaj/mtproto@v0.0.0-20201017141006-a06726563eb1/mtproto_utils.go:77 +0x19c
panic(0xf9a9e0, 0xc0004e20e0)
	C:/Go/src/runtime/panic.go:975 +0x4c7
github.com/xelaj/mtproto.(*MTProto).processResponse(0xc000228360, 0x5f93e7b2069a8001, 0x6, 0x103b8a0, 0xc00022a000, 0x0, 0x0)
	C:/Users/Артем/go/pkg/mod/github.com/xelaj/mtproto@v0.0.0-20201017141006-a06726563eb1/mtproto.go:316 +0x1307
github.com/xelaj/mtproto.(*MTProto).startReadingResponses.func1(0xc000228360, 0x103bce0, 0xc0002f2fc0)
	C:/Users/Артем/go/pkg/mod/github.com/xelaj/mtproto@v0.0.0-20201017141006-a06726563eb1/mtproto.go:243 +0x50b
created by github.com/xelaj/mtproto.(*MTProto).startReadingResponses
	C:/Users/Артем/go/pkg/mod/github.com/xelaj/mtproto@v0.0.0-20201017141006-a06726563eb1/mtproto.go:220 +0x5a
```

callstack:
![image](https://user-images.githubusercontent.com/15386101/97077656-214c9980-15ee-11eb-8f5c-c89d1172f887.png)

panic occurs when calling various methods in a row, for example, authorization and `AccountInitTakeoutSession`  or `AccountInitTakeoutSession` and `MakeRequestAsSlice`, adding Sleep between calls helps

```go
client, err := auth() // method body is taken from here https://github.com/xelaj/mtproto/tree/master/examples/auth
dry.PanicIfErr(err)

//time.Sleep(time.Second)

resp, err := client.AccountInitTakeoutSession(&telegram.AccountInitTakeoutSessionParams{
	Contacts: true,
})
dry.PanicIfErr(err)
```

**Comment by ololosha228** [comment]
@LazarenkoA  i got this panic too, it's happen cause telegram send BadMsgNotification.

I don't know how to process this message. TDlib say that we need just delete current session **completely** and create new one + authorize via phone code, which is too dumb way to process it.

If you found any solutions, please let me know, cause it's really important and urgent bug.

**Comment by LazarenkoA** [comment]
only with sleep (add it before every call to the mtproto method)

**Comment by ololosha228** [comment]
@LazarenkoA  but this is pretty stupid solution)))

I think, that `MTProto` need `sync.Mutex` for requests. Looks like we have race for seqno value
