### ISSUE TITLE
Code quality: telegram package has much debug stuff

### ISSUE THREAD

**Issue by artem-webdev** [xelaj/mtproto#36]
# until I figured out the code generation I will describe here

### 1) there is no point in calling it here
      
     client.AddCustomServerRequestHandler(client.handleSpecialRequests())

### if it makes sense, it still looks like debug prints 
     func (c *Client) handleSpecialRequests() func(interface{}) bool {
	return func(i interface{}) bool {
		switch msg := i.(type) {
		case *UpdatesObj:
			pp.Println(msg, "UPDATE")
			return true
		case *UpdateShort:
			pp.Println(msg, "SHORT UPDATE")
			return true
		}

		return false
	}
      }

###  2) this piece is like debugging in development 

    resp, err := client.InvokeWithLayer(ApiVersion, &InitConnectionParams{
		ApiID:          int32(c.AppID),
		DeviceModel:    c.DeviceModel,
		SystemVersion:  c.SystemVersion,
		AppVersion:     c.AppVersion,
		SystemLangCode: "en", // can't be edited, cause docs says that a single possible parameter
		LangCode:       "en",
		Query:          &HelpGetConfigParams{},
	})

	if err != nil {
		return nil, errors.Wrap(err, "getting server configs")
	}

	config, ok := resp.(*Config)
	if !ok {
		return nil, errors.New("got wrong response: " + reflect.TypeOf(resp).String())
	}

	pp.Println(config)

# 3)
  https://github.com/xelaj/mtproto/blob/1423372456f0469a3bf1e633fb82545d8381d9b5/telegram/common.go#L64

**Comment by ololosha228** [comment]
1) yes, it's looks likes debug, but they are real update messages, which server sends to client.

I need to add methods like `client.OnUserOnline(f func(interface{}))`, `client.OnNewMessage(f func(interface{}))`, `client.OnChannelBlocked(f func(interface{}))` etc. Just wait for it.

2) no, config is also for client specific purposes, i just don't have enough time to fix it, to be honest.

**Comment by artem-webdev** [comment]
I will gladly put in suggestions, but I haven’t figured out code generation yet

**Comment by artem-webdev** [comment]
# this must be hidden from external api
config, ok := resp.(*Config)
if !ok {
	return nil, errors.New("got wrong response: " + reflect.TypeOf(resp).String())
}

**Comment by artem-webdev** [comment]
#client.OnNewMessage is cool, I would like something like this
 client.OnNewMessageText,client.OnNewMessageMedia,client.OnNewMessageVoice  etc .....
