### ISSUE TITLE
Two-steps verification is enabled and a password is required

### ISSUE THREAD

**Issue by musazadeh** [xelaj/mtproto#38]
Hi, can you give me an example of a two-step verification? 

```
$ go run auth.go 99xxxxxxxxxx
...
nil &errors.withStack{
  error: &errors.withMessage{
    cause: &mtproto.ErrResponseCode{
      Code:        401,
      Message:     "SESSION_PASSWORD_NEEDED",
      Description: "Two-steps verification is enabled and a password is required",
    },
    msg: "sedning AuthSignIn",
  },
  stack: &errors.stack{
    0x61786970c4,
    0x61786c7f68,
    0x617845d26c,
    0x6178489454,
  },
}
```

**Comment by ololosha228** [comment]
Hey @musazadeh thanks for questioning!

I currently working on reviewing #28, i'll trying to do my best for merging it as fast as i can!

By the way, you can actually help me by just cloning this PR, experiment with it and give feedback, it helps me merge into master more fast
