### ISSUE TITLE
Codegen: unnecessary strict validation rules for int32 in structs

### ISSUE THREAD

**Issue by kochetkov-av** [xelaj/mtproto#44]
Let's take this piece of code for example:

https://github.com/xelaj/mtproto/blob/b166a10d7c323689e0dd33f5cb61025d40ede778/telegram/methods.go#L3762-L3771

For most of these fields default zero value is totally acceptable. The same goes for most structs.
I believe this should be changed in the generator.

**Comment by ololosha228** [comment]
Hey @kochetkov-av!

Yeah, this will remove when new codegen tool will merge into master. As soon as possible we'll fix it.

I'll close this issue, cause it's already fixed, but not in master, you just need to wait a bit

**Comment by airani** [comment]
Hey @ololosha228 
When do you think this problem will be solved? this is so seriously

**Comment by airani** [comment]
Also this validation not accept zero as value but I should send zero for some fields like this :disappointed: 

```
Key: 'MessagesGetHistoryParams.AddOffset' Error:Field validation for 'AddOffset' failed on the 'required' tag
```

**Comment by ololosha228** [comment]
@airani yeah, it's fixed on 100% with new tl encoder and removing playground validator from deps.

# SIPLEST FIXING HOWTO:

1) generated code is just generated, you are able to modify it for your purposes
2) thanks this, delete `validator` tags and valifator will not warn you.

**Note that next version will not have this problem**, package is 0.x version when i writing this comment, so we'll definetly create more cool api.

**Comment by airani** [comment]
Thanks @ololosha228 
I waiting for next version because I want working with this package in production mode

**Comment by ololosha228** [comment]
@airani actualy last thing (i mean, it's **definetly last**) todo — rework codegen tool, and we ready to 1.0

Btw, at least 3 companies using this package in business apps (Xelaj software, KHS films and 1 more), so i can guarantee that this lib is production-ready (current api is unstable only, everything else works great)

**Comment by airani** [comment]
Hi @ololosha228 
I was checking new methods and structs that generated at new branch and I saw an issue at [this line](https://github.com/xelaj/mtproto/blob/new_decoder_refactoring/telegram/methods_gen.go#L5594) 

```go
type MessagesGetHistoryParams struct {
	Peer       InputPeer
	OffsetID   int32
	OffsetDate int32
	AddOffset  int32
	Limit      int32
	MaxID      int32
	MinID      int32
	Hash       int32
}
```
default values of these `int32` fields are always zero and we need in any different use case just send some fields not sending all fields always with zero value and I think this will be resolved with this change:

```go
type MessagesGetHistoryParams struct {
	Peer       InputPeer
	OffsetID   *int32
	OffsetDate *int32
	AddOffset  int32
	Limit      int32
	MaxID      *int32
	MinID      *int32
	Hash       *int32
}
```
something like this

what do you think?

**Comment by ololosha228** [comment]
@airani well, idea is great, but it looks pretty messy, i think.

Also, TL don't know what is nil or null exactly, so it could make encoding process.

Also, check out [this branch](https://git.io/JIeTz) it'll be merged into master as 1.0 release, also it doesn't have playground validation at all, maybe that's what you are looking)

**Comment by airani** [comment]
> Btw, check out [this branch](https://git.io/JIeTz) it'll be merged into master as 1.0 release, it doesn't have playground validation at all, maybe that's what you are looking)

@ololosha228 I saw this branch and this problem still exists at this branch in [this line](https://github.com/xelaj/mtproto/blob/new_decoder_refactoring/telegram/methods_gen.go#L5594) for example

**Comment by ololosha228** [comment]
@airani 
how to call:
``` go
res, err := client.MessagesGetHistory(&telegram.MessagesGetHistoryParams{Offset:10})
```

Bingo, you discovered optional arguments)

I hope, that you understanding, that problem in prechecking arguments can't be generated due to tl schema doesn't support prechecking. I hope that we can make it, but at current time, it's not possible.

Also, as i said, TL serialization doesn't understand differences between `uint32(o)` and `&uint32(nil)`, it's anyway using `[]byte{0x0,0x0,0x0,0x0}` as nil value, so use *int32 not so necessary. Especialy in methods with large amount of arguments

**Comment by airani** [comment]
@airani this is a major problem my friend

for example I called this request

```go
res, err := client.MessagesGetHistory(&telegram.MessagesGetHistoryParams{
		Peer: &telegram.InputPeerChannel{
			ChannelId:  channel.TelegramID,
			AccessHash: channel.AccessHash,
		},
		Limit: 100,
                OffsetId: 12,
	})
```
and I want messages after messageID `12` but this code actually sent `OffsetId:12` and `OffsetDate:0` and TL priority with `OffsetDate` and this request not worked correctly!

but with my custom changes that works correctly like this:

```go 
type MessagesGetHistoryParams struct {
	Peer           InputPeer `validate:"required"`
	OffsetId      *int32
	OffsetDate *int32
        // ....
}

func (e *MessagesGetHistoryParams) Encode() []byte {
	err := validator.New().Struct(e)
	dry.PanicIfErr(err)

	buf := serialize.NewEncoder()
	buf.PutUint(e.CRC())
	buf.PutRawBytes(e.Peer.Encode())
        if e.OffsetDate != nil {
                buf.PutInt(*e.OffsetId)
        }
	if e.OffsetDate != nil {
		buf.PutInt(*e.OffsetDate)
	}
        // ...
}
```

I hope understand me and my solution my friend :)

**Comment by ololosha228** [comment]
@airani oooooooh okaaaay, now i got it....

**Comment by airani** [comment]
@ololosha228 Thank you , that's an important problem
