### ISSUE TITLE
Bad Server salt

### ISSUE THREAD

**Issue by patrikhermansson** [xelaj/mtproto#48]
After a few minutes of running the client (using the this [branch](https://github.com/xelaj/mtproto/commit/6582c6e8201a976c56219655838c6b03d784c711)) I get a `BadServerSalt` error message in the console. After that updates stops coming through even if new messages should come in so it doesn't recover from this error correctly. Sometimes this comes very soon after launch, sometimes it takes 10-20 minutes. Wondering if it's the same issue as in [this](https://github.com/zerobias/telegram-mtproto/issues/99) other mtproto project.

`&objects.BadServerSalt{
  BadMsgID:    6900221413643567928,
  BadMsgSeqNo: 1,
  ErrorCode:   48,
  NewSalt:     -4820136725389948751,
} nil`

**Comment by ololosha228** [comment]
Hey @patrikhermansson, sorry for too late response, but i came back)

It looks like internal messages processor doesn't expect `BadServerSalt` as internal error. I'll inspect it and let you know, thanks for creating this issue!

**Comment by ololosha228** [comment]
@patrikhermansson this bug is fixed with latest 1.0rc branch commit, thanks a lot!
