### ISSUE TITLE
Is this repo couldn't run on windows?

### ISSUE THREAD

**Issue by abserari** [xelaj/mtproto#52]
go run .\main.go
panic: not implemented for windows

goroutine 1 [running]:
github.com/xelaj/go-dry.pathIsWirtable(...)
        D:/gopath/src/github.com/abserari/golangbot/vendor/github.com/xelaj/go-dry/path_windows.go:11        
github.com/xelaj/go-dry.PathIsWirtable(...)
        D:/gopath/src/github.com/abserari/golangbot/vendor/github.com/xelaj/go-dry/path.go:44
github.com/xelaj/mtproto/telegram.NewClient(0x8054c0, 0xe, 0x807247, 0x12, 0x803e67, 0xa, 0x0, 0x0, 0x0, 0x0, ...)
        D:/gopath/src/github.com/abserari/golangbot/vendor/github.com/xelaj/mtproto/telegram/common.go:41 +0x172
main.main()
        D:/gopath/src/github.com/abserari/golangbot/mtproto/auth_bot/main.go:30 +0x178
exit status 2

**Comment by quenbyako** [comment]
Hey @abserari thanks for ask!

This is only one thing which is not implemented in windows: our team working only on osx and linux, so we don't know, how to implement checking path permissions to specific user.

If you know how to implement it, or maybe know, which package provide this feature, you can post it here or even create a new PR, any contribution is welcome!

**Comment by abserari** [comment]
![image](https://user-images.githubusercontent.com/32089134/103484124-662f5080-4e27-11eb-87b1-890b3b3f20f1.png)
and I run on wsl (the windows linux subsystem) with ubuntu bash. both windows and wsl get this error. Is this problem about my network?

**Comment by quenbyako** [comment]
@abserari looks like it is 😕😕😕😕 i see tcp problem first time with this package, so i think, that your network connection maybe was broken

**Comment by abserari** [comment]
Because my location, I use proxy. It seems that TCP connection not established on my proxy. 
So I move to a VM on cloud, run same main.go. And get 
![image](https://user-images.githubusercontent.com/32089134/103496140-14fb7d00-4e78-11eb-9ce7-8b3216befc33.png)

**Comment by abserari** [comment]
Now, A New error 
![image](https://user-images.githubusercontent.com/32089134/103496719-3493a500-4e7a-11eb-922e-10d2ad024c64.png)
. ResolveUsername error: sedning ContactsResolveUsername: The user whose identity is being used to execute queries is associated with DC 5 (code 303)

**Comment by quenbyako** [comment]
@abserari looks like a bug, which we'd fixed in november.

Are you using release candidate branch of this package? if not, checkout to [this one](https://github.com/xelaj/mtproto/tree/new_decoder_refactoring) (sorry, this lib is pretty fresh and in active testing, we are going to release after getting a few  more responses about its stability)

If you're using exactly this branch, ping me, i'll look into it.

**Comment by abserari** [comment]
I check out to 
```
[abserari@acat auth_bot]$ go get github.com/xelaj/mtproto@new_decoder_refactoring
go: github.com/xelaj/mtproto new_decoder_refactoring => v0.0.0-20201223190556-d68254027d00
go: downloading github.com/xelaj/mtproto v0.0.0-20201223190556-d68254027d00
```
after update some parameter, change it to string, int per parameter from a structure. 

and got same error
```
[abserari@acat auth_bot]$ go run main.go 
2556426
session created
ResolveUsername error: sending ContactsResolveUsername: The user whose identity is being used to execute queries is associated with DC 5 (code 303)
exit status 1
```

**Comment by abserari** [comment]
Should I change a dc IP address to connect?
 now is 149.154.167.40:443

**Comment by jaskaranSM** [comment]
> ![image](https://user-images.githubusercontent.com/32089134/103484124-662f5080-4e27-11eb-87b1-890b3b3f20f1.png)
> and I run on wsl (the windows linux subsystem) with ubuntu bash. both windows and wsl get this error. Is this problem about my network?

i run on wsl too, haven't seen a single wsarecv error

**Comment by abserari** [comment]
> > ![image](https://user-images.githubusercontent.com/32089134/103484124-662f5080-4e27-11eb-87b1-890b3b3f20f1.png)
> > and I run on wsl (the windows linux subsystem) with ubuntu bash. both windows and wsl get this error. Is this problem about my network?
> 
> i run on wsl too, haven't seen a single wsarecv error

maybe it because of my network. In my region, I couldn't get touch with telegram?

**Comment by abserari** [comment]
When I use Phonenumber auth. I always get this error.
![Uploading image.png…]()

**Comment by quenbyako** [comment]
@abserari i've created really dumb way of fixing this problem, [here is commit of go-dry](https://github.com/xelaj/go-dry/commit/ba7bf81317ba2548d4baca6fce363afe341ceb25) which is handles unimplemented windows file permission checking.

Note, that this update made ONLY for current windows supporting natively, so mtproto is still supporting windows in experiment nonguarantee way.
