### ISSUE TITLE
Unexpected error!

### ISSUE THREAD

**Issue by airani** [xelaj/mtproto#56]
```go
[]uint8{
  0x00, 0x00, 0x00, 0x00,
} &errors.errorString{
  s: "EOF",
}
```

I don't know what is this and I don't know why printed in console when program running and then mtproto client not works!
printed in console without any sign for debug! I confused! anyone can help me?

**Comment by quenbyako** [comment]
Hey @airani! Could you please attach code snippet from go playground? I must repeat this bug for understanding, what's happen :upside_down_face:

**Comment by quenbyako** [comment]
Closing, cause we don't have enough data to inspect this bug.

@airani you can always reopen issue, if you can add more additional data
