### ISSUE TITLE
[BUG]: panic: (*objects.BadMsgNotification)

### ISSUE THREAD

**Issue by vipho** [xelaj/mtproto#60]
#### Description

panic: (*objects.BadMsgNotification) 0xc00058c430 [recovered]
        panic: (*objects.BadMsgNotification) 0xc00058c430

goroutine 53 [running]:
github.com/xelaj/mtproto.(*MTProto).recoverGoroutine(0xc000450900)
        /Users/vipho/go/pkg/mod/github.com/xelaj/mtproto@v1.0.0/mtproto_utils.go:86 +0x125
panic(0x180dc20, 0xc00058c430)
        /usr/local/Cellar/go/1.15.7/libexec/src/runtime/panic.go:969 +0x1b9
github.com/xelaj/mtproto.(*MTProto).processResponse(0xc000450900, 0x1a86fe0, 0xc0000fc070, 0x0, 0x0)
        /Users/vipho/go/pkg/mod/github.com/xelaj/mtproto@v1.0.0/mtproto.go:346 +0x64a
github.com/xelaj/mtproto.(*MTProto).processResponse(0xc000450900, 0x1a86fe0, 0xc0000fc000, 0x88, 0x1a86fe0)
        /Users/vipho/go/pkg/mod/github.com/xelaj/mtproto@v1.0.0/mtproto.go:312 +0x93e
github.com/xelaj/mtproto.(*MTProto).startReadingResponses.func1(0xc000450900, 0x1a89160, 0xc0005ae080)
        /Users/vipho/go/pkg/mod/github.com/xelaj/mtproto@v1.0.0/mtproto.go:289 +0x34b
created by github.com/xelaj/mtproto.(*MTProto).startReadingResponses
        /:257 +0x70
exit status 2

**Comment by quenbyako** [comment]
Hey @vipho, thanks for your feedback!

It looks like #49, so i'll close it as duplicate. You can always reopen if you want to.
