### ISSUE TITLE
[FEAT]: Add chinese readme

### ISSUE THREAD

**Issue by quenbyako** [xelaj/mtproto#77]
## What happened:

We suddenly got a lot of traffic to the repository from China. (来自中国的朋友大家好!) I don’t know what's happened, but it seems that the number of users of this package from China is approximately equal to the Russian ones.

Maybe we should add a translation? Maybe someone wants to help?

**Comment by aofei** [comment]
❤️ Glad you have this idea. I would be happy to help. So this one can be assigned to me. I'll finish it tomorrow (well, it's bedtime now).
