### ISSUE TITLE
[BUG]: missing port in dc list

### ISSUE THREAD

**Issue by xxxsen** [xelaj/mtproto#82]
#### Description

After getting PHONE_MIGRATE_5 err, it would call reconnect with new dc address from dclist, but the format of the ipaddress in dclist is wrong.

in telegram/common.go 
func: NewClient
![image](https://user-images.githubusercontent.com/3880276/113554039-43315a00-962b-11eb-935a-6bcdf6644259.png)

![image](https://user-images.githubusercontent.com/3880276/113554143-6c51ea80-962b-11eb-87df-d3f1dd39498d.png)

valid format should like this:
in utils.go
func: defaultDCList
![image](https://user-images.githubusercontent.com/3880276/113554285-ade29580-962b-11eb-951a-d399851c0333.png)

**Comment by quenbyako** [comment]
@xxxsen yeah, this looks like we misunderstanded migration steps, thanks for notice! I'll fix it!

**Comment by quenbyako** [comment]
@xxxsen Also, if you have some time, create PR, please, i'll merge it

**Comment by khjde1207** [comment]
```
xelaj/mtproto/telegram/common.go 
124 line 
dcList[int(dc.ID)] = dc.IpAddress 
to 
dcList[int(dc.ID)] = dc.IpAddress + ":" + strconv.Itoa(int(dc.Port))

```
I fixed it by modifying the code

**Comment by waybackarchiver** [comment]
Any news here?

**Comment by quenbyako** [comment]
@waybackarchiver thanks for pinging me, i've fixed this error.

Sorry, i might do it way more faster.
